using System;
using System.Collections.Generic;
using System.Text;
using XFTest.Models;

namespace XFTest.Services
{
    public static class DataBaseService
    {
        public static List<CarWashDataContract> CarWashData
        {
            get
            {
                return GetData();
            }
        }

        static List<CarWashDataContract> GetData()
        {
            var data = new List<CarWashDataContract>
            {
                new CarWashDataContract
                {
                    AppliedTime=DateTime.Now,
                     VisitId=new Guid( "799d7830-a5ff-4a0b-b571-9052df6a2e64"),
                     HomeBobEmployeeId=Guid.NewGuid(),
                     HouseOwnerId=Guid.NewGuid(),
                     IsBlocked=false,
                     StartTimeUtc=DateTime.Now.ToString("hh:mm"),
                    EndTimeUtc=DateTime.Now.AddDays(1).ToString("hh:mm"),
                    Title="Add title",
                    IsReviewed= false,
                    IsFirstVisit= false,
                    IsManual=false,
                    VisitTimeUsed= 0,
                    RememberToday= null,
                    HouseOwnerFirstName="Tone",
                    HouseOwnerLastName= "Holtermann",
                    HouseOwnerMobilePhone= "+4520934021",
                    HouseOwnerAddress= "Akademivej 15, 1 th",
                    HouseOwnerZip=2800,
                    HouseOwnerCity= "Kgs. Lyngby",
                    HouseOwnerLatitude= 55.778830,
                    HouseOwnerLongitude= 12.521240,
                    IsSubscriber= false,
                    RememberAlways= null,
                    Professional= "Test",
                    VisitState="ToDo",
                    StateOrder= 1,
                    ExpectedTime=DateTime.Now.AddDays(1). ToString(),
                    Tasks=new List<Task>()
                    {
                        new Task
                        {
                            TaskId=Guid.NewGuid(),
                            Title="Pudsning indvendih",
                            IsTemplate=true,
                            TimesInMinutes=32,
                            Price=22,
                            PaymentTypeId=Guid.NewGuid(),
                            CreateDateUtc=DateTime.Now.AddDays(-3),
                            LastUpdateDateUtc=DateTime.Now,
                            PaymentTypes=null
                        },
                    },
                    HouseOwnerAssets=null,
                    VisitAssets=null,
                    VisitMessages=null
                },
                new CarWashDataContract
                {
                    AppliedTime=DateTime.Now.AddDays(1),
                     VisitId=Guid.NewGuid (),
                     HomeBobEmployeeId=Guid.NewGuid(),
                     HouseOwnerId=Guid.NewGuid(),
                     IsBlocked=false,
                     StartTimeUtc=DateTime.Now.ToString("hh:mm"),
                    EndTimeUtc=DateTime.Now.AddDays(1).ToString("hh:mm"),
                    Title="Add title",
                    IsReviewed= false,
                    IsFirstVisit= false,
                    IsManual=false,
                    VisitTimeUsed= 0,
                    RememberToday= null,
                    HouseOwnerFirstName="Tone",
                    HouseOwnerLastName= "Holtermann",
                    HouseOwnerMobilePhone= "+4520934021",
                    HouseOwnerAddress= "Akademivej 15, 1 th",
                    HouseOwnerZip=2800,
                    HouseOwnerCity= "Kgs. Lyngby",
                    HouseOwnerLatitude= 55.778830,
                    HouseOwnerLongitude= 12.521240,
                    IsSubscriber= false,
                    RememberAlways= null,
                    Professional= "Test",
                    VisitState="InProgress",
                    StateOrder= 1,
                    ExpectedTime=DateTime.Now.AddDays(1). ToString(),
                    Tasks=new List<Task>()
                    {
                        new Task
                        {
                            TaskId=Guid.NewGuid(),
                            Title="Pudsning indvendih",
                            IsTemplate=true,
                            TimesInMinutes=32,
                            Price=22,
                            PaymentTypeId=Guid.NewGuid(),
                            CreateDateUtc=DateTime.Now.AddDays(-3),
                            LastUpdateDateUtc=DateTime.Now,
                            PaymentTypes=null
                        },
                    },
                    HouseOwnerAssets=null,
                    VisitAssets=null,
                    VisitMessages=null
                },
                new CarWashDataContract
                {
                    AppliedTime=DateTime.Now.AddDays(-1),
                     VisitId= Guid.NewGuid (),
                     HomeBobEmployeeId=Guid.NewGuid(),
                     HouseOwnerId=Guid.NewGuid(),
                     IsBlocked=false,
                     StartTimeUtc=DateTime.Now.ToString("hh:mm"),
                    EndTimeUtc=DateTime.Now.AddDays(1).ToString("hh:mm"),
                    Title="Add title",
                    IsReviewed= false,
                    IsFirstVisit= false,
                    IsManual=false,
                    VisitTimeUsed= 0,
                    RememberToday= null,
                    HouseOwnerFirstName="Tone",
                    HouseOwnerLastName= "Holtermann",
                    HouseOwnerMobilePhone= "+4520934021",
                    HouseOwnerAddress= "Akademivej 15, 1 th",
                    HouseOwnerZip=2800,
                    HouseOwnerCity= "Kgs. Lyngby",
                    HouseOwnerLatitude= 55.778830,
                    HouseOwnerLongitude= 12.521240,
                    IsSubscriber= false,
                    RememberAlways= null,
                    Professional= "Test",
                    VisitState="Done",
                    StateOrder= 1,
                    ExpectedTime=DateTime.Now.AddDays(1). ToString(),
                    Tasks=new List<Task>()
                    {
                        new Task
                        {
                            TaskId=Guid.NewGuid(),
                            Title="Pudsning indvendih",
                            IsTemplate=true,
                            TimesInMinutes=32,
                            Price=22,
                            PaymentTypeId=Guid.NewGuid(),
                            CreateDateUtc=DateTime.Now.AddDays(-3),
                            LastUpdateDateUtc=DateTime.Now,
                            PaymentTypes=null
                        },
                    },
                    HouseOwnerAssets=null,
                    VisitAssets=null,
                    VisitMessages=null
                },
                new CarWashDataContract
                {
                    AppliedTime=DateTime.Now.AddDays(2),
                     VisitId=Guid.NewGuid(),
                     HomeBobEmployeeId=Guid.NewGuid(),
                     HouseOwnerId=Guid.NewGuid(),
                     IsBlocked=false,
                     StartTimeUtc=DateTime.Now.ToString("hh:mm"),
                    EndTimeUtc=DateTime.Now.AddDays(1).ToString("hh:mm"),
                    Title="Add title",
                    IsReviewed= false,
                    IsFirstVisit= false,
                    IsManual=false,
                    VisitTimeUsed= 0,
                    RememberToday= null,
                    HouseOwnerFirstName="Tone",
                    HouseOwnerLastName= "Holtermann",
                    HouseOwnerMobilePhone= "+4520934021",
                    HouseOwnerAddress= "Akademivej 15, 1 th",
                    HouseOwnerZip=2800,
                    HouseOwnerCity= "Kgs. Lyngby",
                    HouseOwnerLatitude= 55.778830,
                    HouseOwnerLongitude= 12.521240,
                    IsSubscriber= false,
                    RememberAlways= null,
                    Professional= "Test",
                    VisitState="Rejected",
                    StateOrder= 1,
                    ExpectedTime=DateTime.Now.AddDays(1). ToString(),
                    Tasks=new List<Task>()
                    {
                        new Task
                        {
                            TaskId=Guid.NewGuid(),
                            Title="Pudsning indvendih",
                            IsTemplate=true,
                            TimesInMinutes=32,
                            Price=22,
                            PaymentTypeId=Guid.NewGuid(),
                            CreateDateUtc=DateTime.Now.AddDays(-3),
                            LastUpdateDateUtc=DateTime.Now,
                            PaymentTypes=null
                        },
                    },
                    HouseOwnerAssets=null,
                    VisitAssets=null,
                    VisitMessages=null
                },
                    new CarWashDataContract
                {
                        AppliedTime=DateTime.Now.AddDays(-2),
                     VisitId=new Guid( "799d7830-a5ff-4a0b-b571-9052df6a2e64"),
                     HomeBobEmployeeId=Guid.NewGuid(),
                     HouseOwnerId=Guid.NewGuid(),
                     IsBlocked=false,
                     StartTimeUtc=DateTime.Now.ToString("hh:mm"),
                    EndTimeUtc=DateTime.Now.AddDays(1).ToString("hh:mm"),
                    Title="Add title",
                    IsReviewed= false,
                    IsFirstVisit= false,
                    IsManual=false,
                    VisitTimeUsed= 0,
                    RememberToday= null,
                    HouseOwnerFirstName="Tone",
                    HouseOwnerLastName= "Holtermann",
                    HouseOwnerMobilePhone= "+4520934021",
                    HouseOwnerAddress= "Akademivej 15, 1 th",
                    HouseOwnerZip=2800,
                    HouseOwnerCity= "Kgs. Lyngby",
                    HouseOwnerLatitude= 55.778830,
                    HouseOwnerLongitude= 12.521240,
                    IsSubscriber= false,
                    RememberAlways= null,
                    Professional= "Test",
                    VisitState="Done",
                    StateOrder= 1,
                    ExpectedTime=DateTime.Now.AddDays(1). ToString(),
                    Tasks=new List<Task>()
                    {
                        new Task
                        {
                            TaskId=Guid.NewGuid(),
                            Title="Pudsning indvendih",
                            IsTemplate=true,
                            TimesInMinutes=32,
                            Price=22,
                            PaymentTypeId=Guid.NewGuid(),
                            CreateDateUtc=DateTime.Now.AddDays(-3),
                            LastUpdateDateUtc=DateTime.Now,
                            PaymentTypes=null
                        },
                    },
                    HouseOwnerAssets=null,
                    VisitAssets=null,
                    VisitMessages=null
                },
                     new CarWashDataContract
                {
                         AppliedTime=DateTime.Now.AddDays(3),
                     VisitId=new Guid( "799d7830-a5ff-4a0b-b571-9052df6a2e64"),
                     HomeBobEmployeeId=Guid.NewGuid(),
                     HouseOwnerId=Guid.NewGuid(),
                     IsBlocked=false,
                     StartTimeUtc=DateTime.Now.ToString("hh:mm"),
                    EndTimeUtc=DateTime.Now.AddDays(1).ToString("hh:mm"),
                    Title="Add title",
                    IsReviewed= false,
                    IsFirstVisit= false,
                    IsManual=false,
                    VisitTimeUsed= 0,
                    RememberToday= null,
                    HouseOwnerFirstName="Tone",
                    HouseOwnerLastName= "Holtermann",
                    HouseOwnerMobilePhone= "+4520934021",
                    HouseOwnerAddress= "Akademivej 15, 1 th",
                    HouseOwnerZip=2800,
                    HouseOwnerCity= "Kgs. Lyngby",
                    HouseOwnerLatitude= 55.778830,
                    HouseOwnerLongitude= 12.521240,
                    IsSubscriber= false,
                    RememberAlways= null,
                    Professional= "Test",
                    VisitState="ToDo",
                    StateOrder= 1,
                    ExpectedTime=DateTime.Now.AddDays(1). ToString(),
                    Tasks=new List<Task>()
                    {
                        new Task
                        {
                            TaskId=Guid.NewGuid(),
                            Title="Pudsning indvendih",
                            IsTemplate=true,
                            TimesInMinutes=32,
                            Price=22,
                            PaymentTypeId=Guid.NewGuid(),
                            CreateDateUtc=DateTime.Now.AddDays(-3),
                            LastUpdateDateUtc=DateTime.Now,
                            PaymentTypes=null
                        },
                    },
                    HouseOwnerAssets=null,
                    VisitAssets=null,
                    VisitMessages=null
                },
                new CarWashDataContract
                {
                    AppliedTime=DateTime.Now.AddDays(4),
                     VisitId=new Guid( "799d7830-a5ff-4a0b-b571-9052df6a2e64"),
                     HomeBobEmployeeId=Guid.NewGuid(),
                     HouseOwnerId=Guid.NewGuid(),
                     IsBlocked=false,
                     StartTimeUtc=DateTime.Now.ToString("hh:mm"),
                    EndTimeUtc=DateTime.Now.AddDays(1).ToString("hh:mm"),
                    Title="Add title",
                    IsReviewed= false,
                    IsFirstVisit= false,
                    IsManual=false,
                    VisitTimeUsed= 0,
                    RememberToday= null,
                    HouseOwnerFirstName="Tone",
                    HouseOwnerLastName= "Holtermann",
                    HouseOwnerMobilePhone= "+4520934021",
                    HouseOwnerAddress= "Akademivej 15, 1 th",
                    HouseOwnerZip=2800,
                    HouseOwnerCity= "Kgs. Lyngby",
                    HouseOwnerLatitude= 55.778830,
                    HouseOwnerLongitude= 12.521240,
                    IsSubscriber= false,
                    RememberAlways= null,
                    Professional= "Test",
                    VisitState="Rejected",
                    StateOrder= 1,
                    ExpectedTime=DateTime.Now.AddDays(1). ToString(),
                    Tasks=new List<Task>()
                    {
                        new Task
                        {
                            TaskId=Guid.NewGuid(),
                            Title="Pudsning indvendih",
                            IsTemplate=true,
                            TimesInMinutes=32,
                            Price=22,
                            PaymentTypeId=Guid.NewGuid(),
                            CreateDateUtc=DateTime.Now.AddDays(-3),
                            LastUpdateDateUtc=DateTime.Now,
                            PaymentTypes=null
                        },
                    },
                    HouseOwnerAssets=null,
                    VisitAssets=null,
                    VisitMessages=null
                },
                new CarWashDataContract
                {
                    AppliedTime=DateTime.Now.AddDays(5),
                     VisitId=Guid.NewGuid(),
                     HomeBobEmployeeId=Guid.NewGuid(),
                     HouseOwnerId=Guid.NewGuid(),
                     IsBlocked=false,
                     StartTimeUtc=DateTime.Now.ToString("hh:mm"),
                    EndTimeUtc=DateTime.Now.AddDays(1).ToString("hh:mm"),
                    Title="Add title",
                    IsReviewed= false,
                    IsFirstVisit= false,
                    IsManual=false,
                    VisitTimeUsed= 0,
                    RememberToday= null,
                    HouseOwnerFirstName="Tone",
                    HouseOwnerLastName= "Holtermann",
                    HouseOwnerMobilePhone= "+4520934021",
                    HouseOwnerAddress= "Akademivej 15, 1 th",
                    HouseOwnerZip=2800,
                    HouseOwnerCity= "Kgs. Lyngby",
                    HouseOwnerLatitude= 55.778830,
                    HouseOwnerLongitude= 12.521240,
                    IsSubscriber= false,
                    RememberAlways= null,
                    Professional= "Test",
                    VisitState="ToDo",
                    StateOrder= 1,
                    ExpectedTime=DateTime.Now.AddDays(1). ToString(),
                    Tasks=new List<Task>()
                    {
                        new Task
                        {
                            TaskId=Guid.NewGuid(),
                            Title="Pudsning indvendih",
                            IsTemplate=true,
                            TimesInMinutes=32,
                            Price=22,
                            PaymentTypeId=Guid.NewGuid(),
                            CreateDateUtc=DateTime.Now.AddDays(-3),
                            LastUpdateDateUtc=DateTime.Now,
                            PaymentTypes=null
                        },
                    },
                    HouseOwnerAssets=null,
                    VisitAssets=null,
                    VisitMessages=null
                },
                 new CarWashDataContract
                {
                    AppliedTime=DateTime.Now,
                     VisitId=new Guid( "799d7830-a5ff-4a0b-b571-9052df6a2e64"),
                     HomeBobEmployeeId=Guid.NewGuid(),
                     HouseOwnerId=Guid.NewGuid(),
                     IsBlocked=false,
                     StartTimeUtc=DateTime.Now.ToString("hh:mm"),
                    EndTimeUtc=DateTime.Now.AddDays(1).ToString("hh:mm"),
                    Title="Add title",
                    IsReviewed= false,
                    IsFirstVisit= false,
                    IsManual=false,
                    VisitTimeUsed= 0,
                    RememberToday= null,
                    HouseOwnerFirstName="Tone",
                    HouseOwnerLastName= "Holtermann",
                    HouseOwnerMobilePhone= "+4520934021",
                    HouseOwnerAddress= "Akademivej 15, 1 th",
                    HouseOwnerZip=2800,
                    HouseOwnerCity= "Kgs. Lyngby",
                    HouseOwnerLatitude= 55.778830,
                    HouseOwnerLongitude= 12.521240,
                    IsSubscriber= false,
                    RememberAlways= null,
                    Professional= "Test",
                    VisitState="ToDo",
                    StateOrder= 1,
                    ExpectedTime=DateTime.Now.AddDays(1). ToString(),
                    Tasks=new List<Task>()
                    {
                        new Task
                        {
                            TaskId=Guid.NewGuid(),
                            Title="Pudsning indvendih",
                            IsTemplate=true,
                            TimesInMinutes=32,
                            Price=22,
                            PaymentTypeId=Guid.NewGuid(),
                            CreateDateUtc=DateTime.Now.AddDays(-3),
                            LastUpdateDateUtc=DateTime.Now,
                            PaymentTypes=null
                        },
                    },
                    HouseOwnerAssets=null,
                    VisitAssets=null,
                    VisitMessages=null
                }, new CarWashDataContract
                {
                    AppliedTime=DateTime.Now,
                     VisitId=new Guid( "799d7830-a5ff-4a0b-b571-9052df6a2e64"),
                     HomeBobEmployeeId=Guid.NewGuid(),
                     HouseOwnerId=Guid.NewGuid(),
                     IsBlocked=false,
                     StartTimeUtc=DateTime.Now.ToString("hh:mm"),
                    EndTimeUtc=DateTime.Now.AddDays(1).ToString("hh:mm"),
                    Title="Add title",
                    IsReviewed= false,
                    IsFirstVisit= false,
                    IsManual=false,
                    VisitTimeUsed= 0,
                    RememberToday= null,
                    HouseOwnerFirstName="Tone",
                    HouseOwnerLastName= "Holtermann",
                    HouseOwnerMobilePhone= "+4520934021",
                    HouseOwnerAddress= "Akademivej 15, 1 th",
                    HouseOwnerZip=2800,
                    HouseOwnerCity= "Kgs. Lyngby",
                    HouseOwnerLatitude= 55.778830,
                    HouseOwnerLongitude= 12.521240,
                    IsSubscriber= false,
                    RememberAlways= null,
                    Professional= "Test",
                    VisitState="ToDo",
                    StateOrder= 1,
                    ExpectedTime=DateTime.Now.AddDays(1). ToString(),
                    Tasks=new List<Task>()
                    {
                        new Task
                        {
                            TaskId=Guid.NewGuid(),
                            Title="Pudsning indvendih",
                            IsTemplate=true,
                            TimesInMinutes=32,
                            Price=22,
                            PaymentTypeId=Guid.NewGuid(),
                            CreateDateUtc=DateTime.Now.AddDays(-3),
                            LastUpdateDateUtc=DateTime.Now,
                            PaymentTypes=null
                        },
                    },
                    HouseOwnerAssets=null,
                    VisitAssets=null,
                    VisitMessages=null
                }, new CarWashDataContract
                {
                    AppliedTime=DateTime.Now,
                     VisitId=new Guid( "799d7830-a5ff-4a0b-b571-9052df6a2e64"),
                     HomeBobEmployeeId=Guid.NewGuid(),
                     HouseOwnerId=Guid.NewGuid(),
                     IsBlocked=false,
                     StartTimeUtc=DateTime.Now.ToString("hh:mm"),
                    EndTimeUtc=DateTime.Now.AddDays(1).ToString("hh:mm"),
                    Title="Add title",
                    IsReviewed= false,
                    IsFirstVisit= false,
                    IsManual=false,
                    VisitTimeUsed= 0,
                    RememberToday= null,
                    HouseOwnerFirstName="Tone",
                    HouseOwnerLastName= "Holtermann",
                    HouseOwnerMobilePhone= "+4520934021",
                    HouseOwnerAddress= "Akademivej 15, 1 th",
                    HouseOwnerZip=2800,
                    HouseOwnerCity= "Kgs. Lyngby",
                    HouseOwnerLatitude= 55.778830,
                    HouseOwnerLongitude= 12.521240,
                    IsSubscriber= false,
                    RememberAlways= null,
                    Professional= "Test",
                    VisitState="ToDo",
                    StateOrder= 1,
                    ExpectedTime=DateTime.Now.AddDays(1). ToString(),
                    Tasks=new List<Task>()
                    {
                        new Task
                        {
                            TaskId=Guid.NewGuid(),
                            Title="Pudsning indvendih",
                            IsTemplate=true,
                            TimesInMinutes=32,
                            Price=22,
                            PaymentTypeId=Guid.NewGuid(),
                            CreateDateUtc=DateTime.Now.AddDays(-3),
                            LastUpdateDateUtc=DateTime.Now,
                            PaymentTypes=null
                        },
                    },
                    HouseOwnerAssets=null,
                    VisitAssets=null,
                    VisitMessages=null
                }, new CarWashDataContract
                {
                    AppliedTime=DateTime.Now,
                     VisitId=new Guid( "799d7830-a5ff-4a0b-b571-9052df6a2e64"),
                     HomeBobEmployeeId=Guid.NewGuid(),
                     HouseOwnerId=Guid.NewGuid(),
                     IsBlocked=false,
                     StartTimeUtc=DateTime.Now.ToString("hh:mm"),
                    EndTimeUtc=DateTime.Now.AddDays(1).ToString("hh:mm"),
                    Title="Add title",
                    IsReviewed= false,
                    IsFirstVisit= false,
                    IsManual=false,
                    VisitTimeUsed= 0,
                    RememberToday= null,
                    HouseOwnerFirstName="Tone",
                    HouseOwnerLastName= "Holtermann",
                    HouseOwnerMobilePhone= "+4520934021",
                    HouseOwnerAddress= "Akademivej 15, 1 th",
                    HouseOwnerZip=2800,
                    HouseOwnerCity= "Kgs. Lyngby",
                    HouseOwnerLatitude= 55.778830,
                    HouseOwnerLongitude= 12.521240,
                    IsSubscriber= false,
                    RememberAlways= null,
                    Professional= "Test",
                    VisitState="ToDo",
                    StateOrder= 1,
                    ExpectedTime=DateTime.Now.AddDays(1). ToString(),
                    Tasks=new List<Task>()
                    {
                        new Task
                        {
                            TaskId=Guid.NewGuid(),
                            Title="Pudsning indvendih",
                            IsTemplate=true,
                            TimesInMinutes=32,
                            Price=22,
                            PaymentTypeId=Guid.NewGuid(),
                            CreateDateUtc=DateTime.Now.AddDays(-3),
                            LastUpdateDateUtc=DateTime.Now,
                            PaymentTypes=null
                        },
                    },
                    HouseOwnerAssets=null,
                    VisitAssets=null,
                    VisitMessages=null
                }, new CarWashDataContract
                {
                    AppliedTime=DateTime.Now,
                     VisitId=new Guid( "799d7830-a5ff-4a0b-b571-9052df6a2e64"),
                     HomeBobEmployeeId=Guid.NewGuid(),
                     HouseOwnerId=Guid.NewGuid(),
                     IsBlocked=false,
                     StartTimeUtc=DateTime.Now.ToString("hh:mm"),
                    EndTimeUtc=DateTime.Now.AddDays(1).ToString("hh:mm"),
                    Title="Add title",
                    IsReviewed= false,
                    IsFirstVisit= false,
                    IsManual=false,
                    VisitTimeUsed= 0,
                    RememberToday= null,
                    HouseOwnerFirstName="Tone",
                    HouseOwnerLastName= "Holtermann",
                    HouseOwnerMobilePhone= "+4520934021",
                    HouseOwnerAddress= "Akademivej 15, 1 th",
                    HouseOwnerZip=2800,
                    HouseOwnerCity= "Kgs. Lyngby",
                    HouseOwnerLatitude= 55.778830,
                    HouseOwnerLongitude= 12.521240,
                    IsSubscriber= false,
                    RememberAlways= null,
                    Professional= "Test",
                    VisitState="ToDo",
                    StateOrder= 1,
                    ExpectedTime=DateTime.Now.AddDays(1). ToString(),
                    Tasks=new List<Task>()
                    {
                        new Task
                        {
                            TaskId=Guid.NewGuid(),
                            Title="Pudsning indvendih",
                            IsTemplate=true,
                            TimesInMinutes=32,
                            Price=22,
                            PaymentTypeId=Guid.NewGuid(),
                            CreateDateUtc=DateTime.Now.AddDays(-3),
                            LastUpdateDateUtc=DateTime.Now,
                            PaymentTypes=null
                        },
                    },
                    HouseOwnerAssets=null,
                    VisitAssets=null,
                    VisitMessages=null
                }, new CarWashDataContract
                {
                    AppliedTime=DateTime.Now,
                     VisitId=new Guid( "799d7830-a5ff-4a0b-b571-9052df6a2e64"),
                     HomeBobEmployeeId=Guid.NewGuid(),
                     HouseOwnerId=Guid.NewGuid(),
                     IsBlocked=false,
                     StartTimeUtc=DateTime.Now.ToString("hh:mm"),
                    EndTimeUtc=DateTime.Now.AddDays(1).ToString("hh:mm"),
                    Title="Add title",
                    IsReviewed= false,
                    IsFirstVisit= false,
                    IsManual=false,
                    VisitTimeUsed= 0,
                    RememberToday= null,
                    HouseOwnerFirstName="Tone",
                    HouseOwnerLastName= "Holtermann",
                    HouseOwnerMobilePhone= "+4520934021",
                    HouseOwnerAddress= "Akademivej 15, 1 th",
                    HouseOwnerZip=2800,
                    HouseOwnerCity= "Kgs. Lyngby",
                    HouseOwnerLatitude= 55.778830,
                    HouseOwnerLongitude= 12.521240,
                    IsSubscriber= false,
                    RememberAlways= null,
                    Professional= "Test",
                    VisitState="ToDo",
                    StateOrder= 1,
                    ExpectedTime=DateTime.Now.AddDays(1). ToString(),
                    Tasks=new List<Task>()
                    {
                        new Task
                        {
                            TaskId=Guid.NewGuid(),
                            Title="Pudsning indvendih",
                            IsTemplate=true,
                            TimesInMinutes=32,
                            Price=22,
                            PaymentTypeId=Guid.NewGuid(),
                            CreateDateUtc=DateTime.Now.AddDays(-3),
                            LastUpdateDateUtc=DateTime.Now,
                            PaymentTypes=null
                        },
                    },
                    HouseOwnerAssets=null,
                    VisitAssets=null,
                    VisitMessages=null
                }, new CarWashDataContract
                {
                    AppliedTime=DateTime.Now,
                     VisitId=new Guid( "799d7830-a5ff-4a0b-b571-9052df6a2e64"),
                     HomeBobEmployeeId=Guid.NewGuid(),
                     HouseOwnerId=Guid.NewGuid(),
                     IsBlocked=false,
                     StartTimeUtc=DateTime.Now.ToString("hh:mm"),
                    EndTimeUtc=DateTime.Now.AddDays(1).ToString("hh:mm"),
                    Title="Add title",
                    IsReviewed= false,
                    IsFirstVisit= false,
                    IsManual=false,
                    VisitTimeUsed= 0,
                    RememberToday= null,
                    HouseOwnerFirstName="Tone",
                    HouseOwnerLastName= "Holtermann",
                    HouseOwnerMobilePhone= "+4520934021",
                    HouseOwnerAddress= "Akademivej 15, 1 th",
                    HouseOwnerZip=2800,
                    HouseOwnerCity= "Kgs. Lyngby",
                    HouseOwnerLatitude= 55.778830,
                    HouseOwnerLongitude= 12.521240,
                    IsSubscriber= false,
                    RememberAlways= null,
                    Professional= "Test",
                    VisitState="ToDo",
                    StateOrder= 1,
                    ExpectedTime=DateTime.Now.AddDays(1). ToString(),
                    Tasks=new List<Task>()
                    {
                        new Task
                        {
                            TaskId=Guid.NewGuid(),
                            Title="Pudsning indvendih",
                            IsTemplate=true,
                            TimesInMinutes=32,
                            Price=22,
                            PaymentTypeId=Guid.NewGuid(),
                            CreateDateUtc=DateTime.Now.AddDays(-3),
                            LastUpdateDateUtc=DateTime.Now,
                            PaymentTypes=null
                        },
                    },
                    HouseOwnerAssets=null,
                    VisitAssets=null,
                    VisitMessages=null
                }, new CarWashDataContract
                {
                    AppliedTime=DateTime.Now.AddDays(12),
                     VisitId=new Guid( "799d7830-a5ff-4a0b-b571-9052df6a2e64"),
                     HomeBobEmployeeId=Guid.NewGuid(),
                     HouseOwnerId=Guid.NewGuid(),
                     IsBlocked=false,
                     StartTimeUtc=DateTime.Now.ToString("hh:mm"),
                    EndTimeUtc=DateTime.Now.AddDays(1).ToString("hh:mm"),
                    Title="Add title",
                    IsReviewed= false,
                    IsFirstVisit= false,
                    IsManual=false,
                    VisitTimeUsed= 0,
                    RememberToday= null,
                    HouseOwnerFirstName="Tone",
                    HouseOwnerLastName= "Holtermann",
                    HouseOwnerMobilePhone= "+4520934021",
                    HouseOwnerAddress= "Akademivej 15, 1 th",
                    HouseOwnerZip=2800,
                    HouseOwnerCity= "Kgs. Lyngby",
                    HouseOwnerLatitude= 55.778830,
                    HouseOwnerLongitude= 12.521240,
                    IsSubscriber= false,
                    RememberAlways= null,
                    Professional= "Test",
                    VisitState="ToDo",
                    StateOrder= 1,
                    ExpectedTime=DateTime.Now.AddDays(1). ToString(),
                    Tasks=new List<Task>()
                    {
                        new Task
                        {
                            TaskId=Guid.NewGuid(),
                            Title="Pudsning indvendih",
                            IsTemplate=true,
                            TimesInMinutes=32,
                            Price=22,
                            PaymentTypeId=Guid.NewGuid(),
                            CreateDateUtc=DateTime.Now.AddDays(-3),
                            LastUpdateDateUtc=DateTime.Now,
                            PaymentTypes=null
                        },
                    },
                    HouseOwnerAssets=null,
                    VisitAssets=null,
                    VisitMessages=null
                }, new CarWashDataContract
                {
                    AppliedTime=DateTime.Now.AddDays(4),
                     VisitId=new Guid( "799d7830-a5ff-4a0b-b571-9052df6a2e64"),
                     HomeBobEmployeeId=Guid.NewGuid(),
                     HouseOwnerId=Guid.NewGuid(),
                     IsBlocked=false,
                     StartTimeUtc=DateTime.Now.ToString("hh:mm"),
                    EndTimeUtc=DateTime.Now.AddDays(1).ToString("hh:mm"),
                    Title="Add title",
                    IsReviewed= false,
                    IsFirstVisit= false,
                    IsManual=false,
                    VisitTimeUsed= 0,
                    RememberToday= null,
                    HouseOwnerFirstName="Tone",
                    HouseOwnerLastName= "Holtermann",
                    HouseOwnerMobilePhone= "+4520934021",
                    HouseOwnerAddress= "Akademivej 15, 1 th",
                    HouseOwnerZip=2800,
                    HouseOwnerCity= "Kgs. Lyngby",
                    HouseOwnerLatitude= 55.778830,
                    HouseOwnerLongitude= 12.521240,
                    IsSubscriber= false,
                    RememberAlways= null,
                    Professional= "Test",
                    VisitState="ToDo",
                    StateOrder= 1,
                    ExpectedTime=DateTime.Now.AddDays(1). ToString(),
                    Tasks=new List<Task>()
                    {
                        new Task
                        {
                            TaskId=Guid.NewGuid(),
                            Title="Pudsning indvendih",
                            IsTemplate=true,
                            TimesInMinutes=32,
                            Price=22,
                            PaymentTypeId=Guid.NewGuid(),
                            CreateDateUtc=DateTime.Now.AddDays(-3),
                            LastUpdateDateUtc=DateTime.Now,
                            PaymentTypes=null
                        },
                    },
                    HouseOwnerAssets=null,
                    VisitAssets=null,
                    VisitMessages=null
                }, new CarWashDataContract
                {
                    AppliedTime=DateTime.Now.AddDays(9),
                     VisitId=new Guid( "799d7830-a5ff-4a0b-b571-9052df6a2e64"),
                     HomeBobEmployeeId=Guid.NewGuid(),
                     HouseOwnerId=Guid.NewGuid(),
                     IsBlocked=false,
                     StartTimeUtc=DateTime.Now.ToString("hh:mm"),
                    EndTimeUtc=DateTime.Now.AddDays(1).ToString("hh:mm"),
                    Title="Add title",
                    IsReviewed= false,
                    IsFirstVisit= false,
                    IsManual=false,
                    VisitTimeUsed= 0,
                    RememberToday= null,
                    HouseOwnerFirstName="Tone",
                    HouseOwnerLastName= "Holtermann",
                    HouseOwnerMobilePhone= "+4520934021",
                    HouseOwnerAddress= "Akademivej 15, 1 th",
                    HouseOwnerZip=2800,
                    HouseOwnerCity= "Kgs. Lyngby",
                    HouseOwnerLatitude= 55.778830,
                    HouseOwnerLongitude= 12.521240,
                    IsSubscriber= false,
                    RememberAlways= null,
                    Professional= "Test",
                    VisitState="ToDo",
                    StateOrder= 1,
                    ExpectedTime=DateTime.Now.AddDays(1). ToString(),
                    Tasks=new List<Task>()
                    {
                        new Task
                        {
                            TaskId=Guid.NewGuid(),
                            Title="Pudsning indvendih",
                            IsTemplate=true,
                            TimesInMinutes=32,
                            Price=22,
                            PaymentTypeId=Guid.NewGuid(),
                            CreateDateUtc=DateTime.Now.AddDays(-3),
                            LastUpdateDateUtc=DateTime.Now,
                            PaymentTypes=null
                        },
                    },
                    HouseOwnerAssets=null,
                    VisitAssets=null,
                    VisitMessages=null
                }, new CarWashDataContract
                {
                    AppliedTime=DateTime.Now.AddDays(10),
                     VisitId=new Guid( "799d7830-a5ff-4a0b-b571-9052df6a2e64"),
                     HomeBobEmployeeId=Guid.NewGuid(),
                     HouseOwnerId=Guid.NewGuid(),
                     IsBlocked=false,
                     StartTimeUtc=DateTime.Now.ToString("hh:mm"),
                    EndTimeUtc=DateTime.Now.AddDays(1).ToString("hh:mm"),
                    Title="Add title",
                    IsReviewed= false,
                    IsFirstVisit= false,
                    IsManual=false,
                    VisitTimeUsed= 0,
                    RememberToday= null,
                    HouseOwnerFirstName="Tone",
                    HouseOwnerLastName= "Holtermann",
                    HouseOwnerMobilePhone= "+4520934021",
                    HouseOwnerAddress= "Akademivej 15, 1 th",
                    HouseOwnerZip=2800,
                    HouseOwnerCity= "Kgs. Lyngby",
                    HouseOwnerLatitude= 55.778830,
                    HouseOwnerLongitude= 12.521240,
                    IsSubscriber= false,
                    RememberAlways= null,
                    Professional= "Test",
                    VisitState="ToDo",
                    StateOrder= 1,
                    ExpectedTime=DateTime.Now.AddDays(1). ToString(),
                    Tasks=new List<Task>()
                    {
                        new Task
                        {
                            TaskId=Guid.NewGuid(),
                            Title="Pudsning indvendih",
                            IsTemplate=true,
                            TimesInMinutes=32,
                            Price=22,
                            PaymentTypeId=Guid.NewGuid(),
                            CreateDateUtc=DateTime.Now.AddDays(-3),
                            LastUpdateDateUtc=DateTime.Now,
                            PaymentTypes=null
                        },
                    },
                    HouseOwnerAssets=null,
                    VisitAssets=null,
                    VisitMessages=null
                }, new CarWashDataContract
                {
                    AppliedTime=DateTime.Now.AddDays(11),
                     VisitId=new Guid( "799d7830-a5ff-4a0b-b571-9052df6a2e64"),
                     HomeBobEmployeeId=Guid.NewGuid(),
                     HouseOwnerId=Guid.NewGuid(),
                     IsBlocked=false,
                     StartTimeUtc=DateTime.Now.ToString("hh:mm"),
                    EndTimeUtc=DateTime.Now.AddDays(1).ToString("hh:mm"),
                    Title="Add title",
                    IsReviewed= false,
                    IsFirstVisit= false,
                    IsManual=false,
                    VisitTimeUsed= 0,
                    RememberToday= null,
                    HouseOwnerFirstName="Tone",
                    HouseOwnerLastName= "Holtermann",
                    HouseOwnerMobilePhone= "+4520934021",
                    HouseOwnerAddress= "Akademivej 15, 1 th",
                    HouseOwnerZip=2800,
                    HouseOwnerCity= "Kgs. Lyngby",
                    HouseOwnerLatitude= 55.778830,
                    HouseOwnerLongitude= 12.521240,
                    IsSubscriber= false,
                    RememberAlways= null,
                    Professional= "Test",
                    VisitState="ToDo",
                    StateOrder= 1,
                    ExpectedTime=DateTime.Now.AddDays(1). ToString(),
                    Tasks=new List<Task>()
                    {
                        new Task
                        {
                            TaskId=Guid.NewGuid(),
                            Title="Pudsning indvendih",
                            IsTemplate=true,
                            TimesInMinutes=32,
                            Price=22,
                            PaymentTypeId=Guid.NewGuid(),
                            CreateDateUtc=DateTime.Now.AddDays(-3),
                            LastUpdateDateUtc=DateTime.Now,
                            PaymentTypes=null
                        },
                    },
                    HouseOwnerAssets=null,
                    VisitAssets=null,
                    VisitMessages=null
                },

            };
           return data;
        }
    }
}
